/***************************************************************
*  DO NOT EDIT THIS FILE!
*         
*  This file is automatically generated by HP Service Test.
*  Manually changing the contents of this file may result in 
*  loss of information.
*          
*  To edit the test, open the file ‘{testName}.st’ 
*  in HP Service Test.
 ***************************************************************/
using System;
using System.Collections.Generic;
using System.Text;

namespace Script
{
    using log4net.Core;

    public delegate void LogTextAppend(string text);

    public class LRAppender  : log4net.Appender.AppenderSkeleton
    {
        public static LogTextAppend logTextAppend;

        protected override void Append(LoggingEvent loggingEvent)
        {
            if (logTextAppend != null)
                logTextAppend(RenderLoggingEvent(loggingEvent));
        }
    }
}
