/***************************************************************
*  DO NOT EDIT THIS FILE!
*         
*  This file is automatically generated by HP Service Test.
*  Manually changing the contents of this file may result in 
*  loss of information.
*          
*  To edit the test, open the file �{testName}.st� 
*  in HP Service Test.
 ***************************************************************/
namespace Script
{
    public partial class VuserClass
    {
        // Insert variable declarations here.
    }
}
