/***************************************************************
*  DO NOT EDIT THIS FILE!
*         
*  This file is automatically generated by HP Service Test.
*  Manually changing the contents of this file may result in 
*  loss of information.
*          
*  To edit the test, open the file ‘{testName}.st’ 
*  in HP Service Test.
 ***************************************************************/
namespace Script
{
    using System;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using System.IO;
    using System.Reflection;

    public partial class VuserClass
    {
        public static ExecutionUnitInput executionUnitInput = null;		

        public int vuser_init()
        {
			lr = new LoadRunner.LrApi(); // Initialize LR-API Interface 
			
			string scriptDir = Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName;
			string log4net_config = string.Empty;
			
			if (lr.get_attrib_string("lr_replay_pipeName") != null)
				log4net_config = Path.Combine(scriptDir, @"Log\vtd_log4loadSTShell.config");
			else
				log4net_config = Path.Combine(scriptDir, @"Log\vtd_log4load.config");
			ctx = new STRunTimeContext(scriptDir, log4net_config);
			
            if (lr.get_debug_message() != 0)
                LRAppender.logTextAppend += SendLogToVugen;

            if (executionUnitInput == null)
            {
                var input = new TestInput();
                input.Load(lr.get_attrib_string("lr_usr_dir"));
				executionUnitInput = input;

                string pipeName = lr.get_attrib_string("lr_replay_pipeName");
                if (pipeName != null && VuserClass.CommandLineArguments == null)
                {
                    VuserClass.CommandLineArguments = new string[2];
                    VuserClass.CommandLineArguments[0] = "-lr_replay_pipeName";
                    VuserClass.CommandLineArguments[1] = pipeName;
                }
            }

			script = new LRWorkFlowScript(ctx);			
			script.InitializeEncryptionManagerValues();
            
            return 0;
        }
    }
}

